In [1]:
import numpy as np
import scipy.linalg

In [2]:
#que eu fiz em outro exercício
#mas parece que não tá tão certo assim

def LUcerto(a):
    n = a.shape[0]
    U = a
    L = np.eye(n)

    for k in range(n-1):
        for i in range(k+1, n):
            m = U[i,k]/U[k,k]
            L[i,k] = m
            for j in range(k+1, n):
                 U[i,j] = U[i,j]-U[k,j]*m

    U = np.triu(U)

    return L, U

In [25]:
#original, oriunda da questao

def LU(A):
    U = np.copy(A)
    m, n = A.shape
    L = np.eye(n)
    for k in range(n-1):
        for j in range(k+1, n):
            L[j,k] = U[j,k]/U[k,k]
            U[j,k+1:n] -= L[j,k]*U[k,k+1:n]
            
    return L, U

In [34]:
def LUin(A):
    m, n = A.shape
    for k in range(n-1):
        for j in range(k+1, n):
            A[j,k] = A[j,k]/A[k,k]
            A[j,k+1:n] -= A[j,k]*A[k,k+1:n]
            
    return np.tril(A,k=-1)+np.eye(n), np.triu(A)

In [40]:
a = np.array([[3., 2., 4.],
              [1., 1., 2.],
              [4., 3., -2.]])

#a = np.random.random((5, 5))
b = a.copy()
c = a.copy()

la, ua = LU(a)
li, ui = LUin(b)
lc, uc = LUcerto(c)

print(la == li)
#print(a)
print(la)
#print(la == lc)
print(np.allclose(la, li))
print(np.allclose(ua, ui))

print(ua)
print(ui)
print(uc)

#ll, uu = scipy.linalg.lu(a, permute_l=True)
#print(ll)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[1.         0.         0.        ]
 [0.33333333 1.         0.        ]
 [1.33333333 1.         1.        ]]
True
False
[[ 3.          2.          4.        ]
 [ 1.          0.33333333  0.66666667]
 [ 4.          0.33333333 -8.        ]]
[[ 3.          2.          4.        ]
 [ 0.          0.33333333  0.66666667]
 [ 0.          0.         -8.        ]]
[[ 3.          2.          4.        ]
 [ 0.          0.33333333  0.66666667]
 [ 0.          0.         -8.        ]]
