Before you turn this problem in, make sure everything runs as expected. First, **restart the kernel** (in the menubar, select Kernel$\rightarrow$Restart) and then **run all cells** (in the menubar, select Cell$\rightarrow$Run All).

Make sure you fill in any place that says `YOUR CODE HERE` or "YOUR ANSWER HERE", as well as your name and collaborators below:

In [1]:
NAME = ""
COLLABORATORS = ""

---

# Exercício Prático 3: PCA

Neste exercício vamos estudar as representações de baixa dimensão obtidas pelo PCA. O objetivo é reproduzir os resultados obtidos usando o módulo sklearn.decomposition.PCA usando apenas o numpy. Para isto, vamos utilizar os dados contidos em ```p1.txt```.

O conjunto de dados ```p1.txt``` contém recordes nacionais femininos em corridas de 100m, 200m e 400m rasos em segundos e corridas de longa distância em minutos. Os nomes das variáveis não estão incluídos.

In [2]:
# lendo os dados
import pandas as pd
import numpy as np
np.set_printoptions(precision=3)

df = pd.read_csv('p1.txt',sep='\t',header=None,names=["Country","100m","200m","400m","800m","1500m","3000m","Marathon"])
df

Country   100m   200m   400m  800m  1500m  3000m  Marathon
0      ARG  10.83  22.67  50.56  2.00   4.09   8.96    153.40
1      AUS  11.12  22.23  48.63  1.98   4.02   8.63    143.51
2      AUT  11.15  22.70  50.62  1.94   4.05   8.78    154.35
3      BEL  11.14  22.48  51.45  1.97   4.08   8.82    143.05
4      BER  11.46  23.05  53.30  2.07   4.29   9.81    174.18
5      BRA  11.17  22.60  50.62  1.97   4.17   9.04    147.41
6      CAN  10.98  22.62  49.91  1.97   4.00   8.54    148.36
7      CHI  11.65  23.84  53.68  2.00   4.22   9.26    152.23
8      CHN  10.79  22.01  49.81  1.93   3.84   8.10    139.39
9      COL  11.31  22.92  49.64  2.04   4.34   9.37    155.19
10     COK  12.52  25.91  61.65  2.28   4.82  11.10    212.33
11     CRC  11.72  23.92  52.57  2.10   4.52   9.84    164.33
12     CZE  11.09  21.97  47.99  1.89   4.03   8.87    145.19
13     DEN  11.42  23.36  52.92  2.02   4.12   8.71    149.34
14     DOM  11.63  23.91  53.02  2.09   4.54   9.89    166.46
15     FIN  11.13  22.39  50.14  2.01   4.10   8.69    148.00
16     FRA  10.73  21.99  48.25  1.94   4.03   8.64    148.27
17     GER  10.81  21.71  47.60  1.92   3.96   8.51    141.45
18     GBR  11.10  22.10  49.43  1.94   3.97   8.37    135.25
19     GRE  11.57  22.94  52.50  2.05   4.25   9.19    150.32
20     GUA  11.92  24.50  55.64  2.15   4.48   9.71    171.33
21     HUN  11.41  23.06  51.50  1.99   4.02   8.55    148.50
22     INA  11.56  23.86  55.08  2.10   4.36   9.50    154.29
23     IND  11.38  22.82  51.05  2.00   4.10   9.11    158.10
24     IRL  11.43  23.02  51.07  2.01   3.98   8.36    142.23
25     ISR  11.45  23.15  52.06  2.07   4.24   9.33    156.36
26     ITA  11.14  22.60  51.31  1.96   3.98   8.59    143.47
27     JPN  11.36  23.33  51.93  2.01   4.16   8.74    139.41
28     KEN  11.62  23.37  51.56  1.97   3.96   8.39    138.47
29    KORN  11.49  23.80  53.67  2.09   4.24   9.01    146.12
30    KORS  11.80  25.10  56.23  1.97   4.25   8.96    145.31
31     LUX  11.76  23.96  56.07  2.07   4.35   9.21    149.23
32     MAS  11.50  23.37  52.56  2.12   4.39   9.31    169.28
33     MRI  11.72  23.83  54.62  2.06   4.33   9.24    167.09
34     MEX  11.09  23.13  48.89  2.02   4.19   8.89    144.06
35     MYA  11.66  23.69  52.96  2.03   4.20   9.08    158.42
36     NED  11.08  22.81  51.35  1.93   4.06   8.57    143.43
37     NZL  11.32  23.13  51.60  1.97   4.10   8.76    146.46
38     NOR  11.41  23.31  52.45  2.03   4.01   8.53    141.06
39     PNG  11.96  24.68  55.18  2.24   4.12  10.21    221.14
40     PHI  11.28  23.35  54.75  2.12   4.41   9.81    165.48
41     POL  10.93  22.13  49.28  1.95   3.99   8.53    144.18
42     POR  11.30  22.88  51.92  1.98   3.96   8.50    143.29
43     ROM  11.30  22.35  49.88  1.92   3.90   8.36    142.50
44     RUS  10.77  21.87  49.11  1.91   3.87   8.38    141.31
45     SAM  12.38  25.45  56.32  2.29   5.92  13.12    191.58
46     SIN  12.13  24.54  55.08  2.12   4.52   9.94    154.41
47     ESP  11.06  22.38  49.67  1.96   4.01   8.48    146.51
48     SWE  11.16  22.82  51.69  1.99   4.09   8.81    150.39
49     SUI  11.34  22.88  51.32  1.98   3.97   8.60    145.51
50     TPE  11.22  22.56  52.74  2.08   4.38   9.63    159.53
51     THA  11.33  23.30  52.60  2.06   4.38  10.07    162.39
52     TUR  11.25  22.71  53.15  2.01   3.92   8.53    151.43
53     USA  10.49  21.34  48.70  1.94   3.95   8.43    139.60

In [3]:
# extraindo a matriz de dados e os nomes dos países
X = df.drop('Country',axis=1).as_matrix()
countries = list(df['Country'])

C:\Users\Administrador.000\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  


## Questão resolvida

Para cada variável (coluna), calcule a média usando ```np.mean``` e a variância usando ```np.var```. Use a função ```np.round``` para arredondar o resultado para 3 casas decimais.

In [4]:
# calculando a média mu e a variância sigma2 (o ddof=1 é usado para que o denominador seja m-1)

mu = np.mean(X,axis=0)
sigma2 = np.var(X,axis=0,ddof=1)

print(mu)
print(sigma2)

[ 11.358  23.119  51.987   2.022   4.189   9.081 153.59 ]
[1.553e-01 8.631e-01 6.761e+00 7.547e-03 9.871e-02 6.648e-01 2.710e+02]


## Questão resolvida

Transforme a matriz ```X``` em ```X_centered``` subtraindo a média de cada variável.

In [5]:
# neste caso, a subtração entre matriz e vetor faz com que o vetor seja subtraído de cada linha da matriz

m,n = X.shape
#Mu = mu.repeat(m).reshape((n,m)).T
X_centered = X-mu
X_centered[:5,:]

array([[ -0.528,  -0.449,  -1.427,  -0.022,  -0.099,  -0.121,  -0.19 ],
       [ -0.238,  -0.889,  -3.357,  -0.042,  -0.169,  -0.451, -10.08 ],
       [ -0.208,  -0.419,  -1.367,  -0.082,  -0.139,  -0.301,   0.76 ],
       [ -0.218,  -0.639,  -0.537,  -0.052,  -0.109,  -0.261, -10.54 ],
       [  0.102,  -0.069,   1.313,   0.048,   0.101,   0.729,  20.59 ]])

## Questão resolvida

Agora normalize a matriz ```X_centered``` dividindo cada entrada pelo seu desvio padrão. Salve o resultado em ```X_normalized```.

In [6]:
# neste caso, a divisão entre matriz e vetor faz com que cada linha da matriz seja dividida elemento-a-elemento pelo vetor

sigma = np.sqrt(sigma2)
#Sigma = sigma.repeat(m).reshape((n,m)).T
X_normalized = X_centered/np.sqrt(sigma2)
X_normalized[:5,:]

array([[-1.339, -0.483, -0.549, -0.258, -0.317, -0.148, -0.012],
       [-0.603, -0.956, -1.291, -0.488, -0.539, -0.553, -0.612],
       [-0.527, -0.45 , -0.526, -0.949, -0.444, -0.369,  0.046],
       [-0.553, -0.687, -0.206, -0.603, -0.348, -0.32 , -0.64 ],
       [ 0.259, -0.074,  0.505,  0.548,  0.32 ,  0.894,  1.251]])

## Questão 1

Defina uma matriz que receba como entrada uma matriz $\mathbf{A}_{m \times n}$ de $m$ observações por $n$ variáveis que já foi centralizada e normalizada e retorne a matriz de covariância das variáveis. A função **não pode** utilizar a função ```numpy.cov```, mas sim utilizar a fórmula vista em sala ($m-1$ como denominador).

In [25]:
def calculaCov(A):
    # YOUR CODE HERE
    m = A.shape[0]
    cov = A.T@A
    cov = cov/(m-1)
    #raise NotImplementedError()
    return cov

Certifique-se de que o resultado para a matriz ```X_normalized``` é igual aquele encontrado no arquivo ```cov.npz```.

In [26]:
cov = calculaCov(X_normalized)
with open('cov.npz','rb') as f: 
    saida = np.load(f)

assert np.allclose(cov,saida)

## Questão 2

Vamos construir a matriz $P = E^\top$ contendo as duas componentes principais. 
Para isso, você deve obter os dois autovetores dos maiores autovalores em módulo da matriz ```cov``` usando ```np.linalg.eig```.

O resultado obtido usando PCA é mostrado a seguir. É possível que alguns autovetores/componentes tenham sinais opostos.

In [ ]:
from sklearn.decomposition import PCA

pca = PCA(n_components=2)
X_r = pca.fit(X_normalized).transform(X_normalized)
pca.components_

In [ ]:
def calculaMatrizP(cov, n_componentes):
    # YOUR CODE HERE
    raise NotImplementedError()
    return P

In [ ]:
P = calculaMatrizP(cov, 2)
print(P)

assert (
    np.allclose(P[0],pca.components_[0]) or np.allclose(P[0],-pca.components_[0])
) and (
    np.allclose(P[1],pca.components_[1]) or np.allclose(P[1],-pca.components_[1])
)

## Questão 3

Calcule a porcentagem da variância total explicada pelo primeiro e segundo componentes principais. Para isto é preciso normalizar os autovalores obtidos no passo anterior pela soma de todos os $n$ autovalores.

O resultado obtido usando PCA é mostrado a seguir.

In [ ]:
pca.explained_variance_ratio_

In [ ]:
def calculaVarianciaExplicada(cov, n_componentes):
    # YOUR CODE HERE
    raise NotImplementedError()
    return var_explicada

In [ ]:
var_explicada = calculaVarianciaExplicada(cov, 2)
assert np.allclose(var_explicada,pca.explained_variance_ratio_)

## Questão 4

As linhas de ```P``` formam uma base ortogonal. A projeção das linhas de ```X_normalized``` nas linhas de ```P``` geram uma representação para cada país no plano (PC1, PC2). Construa um diagrama de dispersão 2D das 54 observações no plano (PC1, PC2).

O resultado obtido usando PCA é mostrado a seguir.

In [ ]:
X_r = pca.fit(X_normalized).transform(X_normalized)
plt.scatter(X_r[:,0],X_r[:,1])
for i in range(X_r.shape[0]):
    plt.annotate(countries[i],xy=(X_r[i,0],X_r[i,1]),xytext=(0,5),
                 textcoords='offset points', ha='center', va='bottom')

In [ ]:
def plotaDiagramaDispersao(P, X_normalized):
    # YOUR CODE HERE
    raise NotImplementedError()

## Questão 5

Considerando o gráfico anterior, que país poderia ser considerado um outlier? O nome do país pode ser consultado [aqui](https://countrycode.org/).

YOUR ANSWER HERE