In [1]:
import numpy as np
import math

In [17]:
def funcao(m):
    W = np.random.randn(m, 4)
    nW = np.divide(W, math.sqrt(m))
    Z = nW.T@nW
    print(Z)
    fro = np.linalg.norm(Z - np.eye(4), 'fro')
    return fro

In [50]:
funcao(10000)

[[ 1.01186808e+00  1.29936257e-02 -2.32190711e-03 -4.74534003e-04]
 [ 1.29936257e-02  9.92605187e-01  5.34173523e-03  1.26787442e-02]
 [-2.32190711e-03  5.34173523e-03  9.78999433e-01  9.99613547e-04]
 [-4.74534003e-04  1.26787442e-02  9.99613547e-04  9.99886899e-01]]


0.0369599862484877