In [1]:
import numpy as np

In [2]:
a = np.array([[3, 4, 3, 1],
              [1, 2, 5, 3],
              [2, 0, 0, 4],
              [1, 0, 0, 1],
              [2, 4, 5, 3]])

mc = np.array([1.8, 3.0, 4.0, 2.4])
ml = np.array([-0.05, -0.05, 0.45, -1.05, 0.7])

In [3]:
#subtraindo as médias de cada coluna

b = a - mc
print("B = ", '\n', b)
print("\n* os elementos b21, b22, b31 e b32 devem ser ignorados")

B =  
 [[ 1.2  1.  -1.  -1.4]
 [-0.8 -1.   1.   0.6]
 [ 0.2 -3.  -4.   1.6]
 [-0.8 -3.  -4.  -1.4]
 [ 0.2  1.   1.   0.6]]

* os elementos b21, b22, b31 e b32 devem ser ignorados


In [4]:
#subtraindo as médias de cada linha

ct = b.T - ml
print("C = ", '\n', ct.T)
print("\n* os elementos c21, c22, c31 e c32 devem ser ignorados")

C =  
 [[ 1.25  1.05 -0.95 -1.35]
 [-0.75 -0.95  1.05  0.65]
 [-0.25 -3.45 -4.45  1.15]
 [ 0.25 -1.95 -2.95 -0.35]
 [-0.5   0.3   0.3  -0.1 ]]

* os elementos c21, c22, c31 e c32 devem ser ignorados


In [26]:
#reconstruindo C pelo seu SVD truncado com k = 2

U = np.array([[-0.62, -0.42],
              [0.47, 0.22],
              [0.5, -0.6],
              [-0.38, 0.19]])

s = np.array([[3.63, 0],
              [0, 1.05]])

Vt = np.array([[-0.38, -0.61, 0.48, 0.51],
               [-0.75, 0.59, 0.28, -0.11]])
ck = U@s@Vt
print(ck)

[[ 1.185978  1.112676 -1.203768 -1.099296]
 [-0.821568 -0.904431  0.883608  0.844701]
 [-0.2172   -1.47885   0.6948    0.99495 ]
 [ 0.374547  0.959139 -0.606252 -0.725439]]


In [36]:
#readicionando as médias que foram retiradas

bk = (ck.T + ml[:4]).T
ak = bk + mc
ak

array([[ 2.835978,  3.962676,  2.646232,  1.150704],
       [ 0.828432,  1.945569,  4.733608,  3.094701],
       [ 2.9328  ,  2.87115 ,  6.0448  ,  4.74495 ],
       [-0.975453,  0.809139,  0.243748, -1.475439]])